// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOfbxPsEY0NmEqKUXx6wLaZ8zJN0h8EwE',
    appId: '1:680836747287:web:7a3982fd1664902706cc52',
    messagingSenderId: '680836747287',
    projectId: 'chat-with-astrologer',
    authDomain: 'chat-with-astrologer.firebaseapp.com',
    storageBucket: 'chat-with-astrologer.appspot.com',
    measurementId: 'G-P4NMBQ06HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBocjWTQ89QHXlCoZgFu57XRxui4psX4lQ',
    appId: '1:680836747287:android:c2fe78b1d50491ea06cc52',
    messagingSenderId: '680836747287',
    projectId: 'chat-with-astrologer',
    storageBucket: 'chat-with-astrologer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsf7bfJfArTH8LXoWui69kbSLZo-s8b9g',
    appId: '1:680836747287:ios:240bd8e87f3baa9506cc52',
    messagingSenderId: '680836747287',
    projectId: 'chat-with-astrologer',
    storageBucket: 'chat-with-astrologer.appspot.com',
    iosBundleId: 'com.ksbm.chatwithastrologer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsf7bfJfArTH8LXoWui69kbSLZo-s8b9g',
    appId: '1:680836747287:ios:d981650ec6d8589e06cc52',
    messagingSenderId: '680836747287',
    projectId: 'chat-with-astrologer',
    storageBucket: 'chat-with-astrologer.appspot.com',
    iosBundleId: 'com.ksbm.chatwithastrologer.RunnerTests',
  );
}
